# Generated by Django 3.1.3 on 2021-11-11 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myLibrary', '0002_book_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('created_at',)},
        ),
        migrations.AddField(
            model_name='book',
            name='published_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
