# Generated by Django 3.1.3 on 2021-12-19 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myLibrary', '0003_auto_20211111_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn13',
            field=models.FloatField(default=0),
        ),
    ]
