# Generated by Django 3.1.3 on 2021-12-30 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myLibrary', '0005_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='published_date',
            field=models.PositiveSmallIntegerField(default=2000),
        ),
    ]
