# Generated by Django 3.1.3 on 2021-12-30 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myLibrary', '0006_auto_20211230_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.TextField(default=''),
        ),
    ]
